// layout.js dosyası içinde
import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import "./globals.css";
import StoreProvider from "./redux/storeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
  <StoreProvider>
  <body>
     <div className='flex flex-col min-h-screen'>
     <Header/>
      <main className='flex-grow'>
      {children}
      </main>
     </div>
     <Footer/>
        </body>
    </StoreProvider> 
    </html>
  )
}