import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import "./globals.css";
import StoreProvider from "@/app/redux/StoreProvider";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
     <StoreProvider>
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
