import Footer from "./components/layout/Footer";
import Header from "./components/layout/Header";
import "./globals.css";
import StoreProvider from "@/app/redux/StoreProvider";
import React from "react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextAuth.js]/route";
import SessionWrapper from "./util/SessionWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);  // authOptions eklenmeli
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          <SessionWrapper>
     <StoreProvider>
            <Header />
            <main className="flex-grow">{children}</main>
            <Footer />
          </StoreProvider>
          </SessionWrapper>
        </div>
      </body>
    </html>
  );
}
